In [1]:
x=7
print(x)

7


In [2]:
'''Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
 Product (prod)
 Multiplication (multiply)
 Dot Product (dot)'''


import numpy as np

# Create two random 3x3 matrices
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)

print("Matrix 1:")
print(matrix1)

print("Matrix 2:")
print(matrix2)

# Perform the requested operations
product_result = np.prod(matrix1)
multiplication_result = np.multiply(matrix1, matrix2)
dot_product_result = np.dot(matrix1, matrix2)

print("Product Result:")
print(product_result)

print("Multiplication Result:")
print(multiplication_result)

print("Dot Product Result:")
print(dot_product_result)

Matrix 1:
[[0.25213022 0.39076443 0.200704  ]
 [0.42620883 0.25844834 0.72242075]
 [0.54140655 0.43419392 0.9959473 ]]
Matrix 2:
[[0.08138518 0.35516279 0.8952612 ]
 [0.22353084 0.39815259 0.73984668]
 [0.1402853  0.17205003 0.92639279]]
Product Result:
0.00036840537692063656
Multiplication Result:
[[0.02051966 0.13878499 0.1796825 ]
 [0.09527082 0.10290188 0.53448059]
 [0.07595138 0.07470308 0.9226384 ]]
Dot Product Result:
[[0.13602338 0.27966227 0.70075891]
 [0.19380327 0.3785679  1.24202575]
 [0.28083496 0.53651566 1.72857562]]


In [3]:
'''Q2. Perform the following set operations using the Numpy functions.
è Union
è Intersection
è Set difference
è XOR
'''
import numpy as np

# Create two NumPy arrays to represent sets
set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([3, 4, 5, 6, 7])

# Union
union_result = np.union1d(set1, set2)
print("Union Result:")
print(union_result)

# Intersection
intersection_result = np.intersect1d(set1, set2)
print("Intersection Result:")
print(intersection_result)

# Set Difference (set1 - set2)
set_difference_result = np.setdiff1d(set1, set2)
print("Set Difference Result (set1 - set2):")
print(set_difference_result)

# XOR (Symmetric Difference)
xor_result = np.setxor1d(set1, set2)
print("XOR (Symmetric Difference) Result:")
print(xor_result)

Union Result:
[1 2 3 4 5 6 7]
Intersection Result:
[3 4 5]
Set Difference Result (set1 - set2):
[1 2]
XOR (Symmetric Difference) Result:
[1 2 6 7]


In [8]:
'''Q3. Create a 1D array using Random function and perform the following operations.
è Cumulative sum
è Cumulative Product
è Discrete difference (with n=3)
è Find the unique elements from the array'''


import numpy as np

# Create a random 1D array with 10 elements
random_array = np.random.rand(10)

print("Original Array:")
print(random_array)

# Cumulative Sum
cumulative_sum = np.cumsum(random_array)
print("Cumulative Sum:")
print(cumulative_sum)

# Cumulative Product
cumulative_product = np.cumprod(random_array)
print("Cumulative Product:")
print(cumulative_product)

# Discrete Difference (with n=3)
n = 3
discrete_difference = np.diff(random_array, n=n)
print(f"Discrete Difference (n={n}):")
print(discrete_difference)

# Find Unique Elements
unique_elements = np.unique(random_array)
print("Unique Elements:")
print(unique_elements)

Original Array:
[0.80244617 0.87084782 0.82984668 0.68302236 0.26278849 0.99385191
 0.1660987  0.02389486 0.54009052 0.91820633]
Cumulative Sum:
[0.80244617 1.67329399 2.50314067 3.18616302 3.44895151 4.44280342
 4.60890212 4.63279698 5.17288751 6.09109384]
Cumulative Product:
[8.02446175e-01 6.98808500e-01 5.79903911e-01 3.96087335e-01
 1.04087192e-01 1.03447255e-01 1.71824547e-02 4.10572363e-04
 2.21746243e-04 2.03608805e-04]
Discrete Difference (n=3):
[ 0.0035796  -0.16758637  1.42470684 -2.71011392  2.24436599 -0.02714986
 -0.79647936]
Unique Elements:
[0.02389486 0.1660987  0.26278849 0.54009052 0.68302236 0.80244617
 0.82984668 0.87084782 0.91820633 0.99385191]


In [6]:
'''Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())'''


import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Perform addition using zip()
addition_zip = [x + y for x, y in zip(array1, array2)]
print("Addition using zip():")
print(addition_zip)

# Perform addition using numpy.add()
addition_np = np.add(array1, array2)
print("Addition using numpy.add():")
print(addition_np)

# Define a user-defined addition function using numpy.frompyfunc()
def custom_add(x, y):
    return x + y

addition_custom = np.frompyfunc(custom_add, 2, 1)(array1, array2)
print("Addition using user-defined function (frompyfunc()):")
print(addition_custom)


Addition using zip():
[7, 9, 11, 13, 15]
Addition using numpy.add():
[ 7  9 11 13 15]
Addition using user-defined function (frompyfunc()):
[7 9 11 13 15]


In [7]:
'''Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().'''

from functools import reduce
import math

# Define a function to find the LCM of two numbers
def lcm(x, y):
    return x * y // math.gcd(x, y)

# Define a function to find the GCD of two numbers
def gcd(x, y):
    return math.gcd(x, y)

# Example array of elements
array = [12, 18, 24, 36]

# Find the LCM of the elements in the array
lcm_result = reduce(lcm, array)

# Find the GCD of the elements in the array
gcd_result = reduce(gcd, array)

print("Array:", array)
print("LCM of the elements:", lcm_result)
print("GCD of the elements:", gcd_result)

Array: [12, 18, 24, 36]
LCM of the elements: 72
GCD of the elements: 6
